### ISSUE TITLE
jQuery cxCalendar的建议

### ISSUE THREAD

**Issue by shibazijun** [ciaoca/cxCalendar#11]
建议：
1、在日期选择面板里增加两个按钮，一个清除按钮， 用于清除上一次选择的时间值，另一个快捷选择今天的按钮；
2、如果type值为：'datetime' 时，修改时间的交互方式不太友好，建议用select标签；
3、新增一个参数，限制不能选取周末；
4、增加一个接口,可以自定义添加哪些日期不让选择（如自定义节假日不让选择）；
5、提供一个回调函数可以获取当前取值为当月和当年的第几周
希望能采纳，谢谢！

**Comment by shibazijun** [comment]
另外补充两个建议：
1、新增一个参数，限制不能选取周末
2、在startDate和endDate 时间段内增加一个接口,可以自定义添加哪些日期不让选择（如自定义节假日不让选择）

**Comment by ciaoca** [comment]
1. 按钮会考虑增加，使用 CSS 来控制是否需要显示。
2. 目前感觉交互还不错， 使用鼠标滚轮可以快速修改时间，单击选中时也会选中全部，直接输入数字。暂时不会使用 select，显示效果恨不美观，至少在 IE9 以下很粗野。
3. 考虑中，会加上
4. 和3是同一个功能
5. 后续尽量补完 format 参数

感谢提建议
