### ISSUE TITLE
报错反馈

### ISSUE THREAD

**Issue by vivine** [ciaoca/cxCalendar#12]
line 358、line 363、line368 创建的是input元素，但用了 .html()，虽然JQ不会出现啥错误，但是当给一个元素使用 .html()  参数传的是一个 undefined 变量的话，会导致后面的appendTo报错，执行不下去。

建议：
1、初始化_html 这个变量的时候 ，把它初始化为空
2、创建完input后不要跟 .html() 函数，即去掉  .html(_html)

**Comment by ciaoca** [comment]
感谢，已删除这部分多余代码
