### ISSUE TITLE
如何触发选择日期后的事件

### ISSUE THREAD

**Issue by xxssww0258** [ciaoca/cxCalendar#14]
比如我要实时修改查询结果，当我点击日期后，立刻要调用我的一个函数，我用react 的 onChange事件取监听 监听不到  源码好像是用html() 实现 这东西好像不能触发事件（具体我也没去试）

**Comment by ciaoca** [comment]
赋值之后会触发 change 事件，监听应该就可以获取
`$('#inputId').on('change', fun)`

**Comment by xxssww0258** [comment]
感谢，我试了一下$('#inputId').on('change', fun)，能监听到事件了，react的onChange被阻止
