### ISSUE TITLE
unday无效

### ISSUE THREAD

**Issue by cat-kun** [ciaoca/cxCalendar#15]
unday使用后无效

**Comment by ciaoca** [comment]
请详细说明

**Comment by cat-kun** [comment]
![qq 20171227095157](https://user-images.githubusercontent.com/8529528/34368024-9f11f4a4-eaeb-11e7-8e35-373e2eb1f7c1.jpg)
unday参数使用后无效

**Comment by ciaoca** [comment]
你这截图，根本看不出来变量 diffStarDate2 是什么值
