### ISSUE TITLE
startDate指定时分秒的bug

### ISSUE THREAD

**Issue by shibazijun** [ciaoca/cxCalendar#17]
var d = new Date()；
d.setHours(9,0,0);
dateFirst.cxCalendar({startDate:d,type:'datetime',format:'YYYY-MM-DD HH:mm:ss'});

startDate 这个参数若只设置 时、分、秒时，
当指定的值大于当前时间则正常，否则就有异常了，正确值应该是第二天的指定时、分、秒

**Comment by ciaoca** [comment]
这是 javascript 的“特性”
