### ISSUE TITLE
today按钮的bug

### ISSUE THREAD

**Issue by shibazijun** [ciaoca/cxCalendar#18]
当点toda 按钮的时候得考虑data-start-date	、data-end-date两个参数的值，如果不在可选范围内，today得隐藏或 return 掉，不让可点。

另外提个建议：
有时候根据业务需要，有些特殊情况，如以下场景：
1、只要选择年
2、只需要月份
3、同时需要年和月
这些是可以考虑完善一下的。谢谢！

**Comment by ciaoca** [comment]
只要年或月一个下拉框就能解决；
年+月，两个下拉框解决；
简单的东西请用简单的方式解决吧
