### ISSUE TITLE
你好，可以设置禁用未来的日期吗

### ISSUE THREAD

**Issue by sunny628** [ciaoca/cxCalendar#19]
你好，可以设置禁用未来的日期吗

**Comment by ciaoca** [comment]
设置参数 `endDate`

**Comment by sunny628** [comment]
![qq 20180525170010](https://user-images.githubusercontent.com/16478878/40536203-ef975406-603d-11e8-9c7c-56acd22081be.png)

我这样设置之后，没有起效？

**Comment by sunny628** [comment]
还是可以选择未来的日期，

**Comment by sunny628** [comment]
`  //日历
        var $startDate = $("#startDate");
        var $endDate = $("#endDate");
        var startTimeApi, endTimeApi;

        $startDate.cxCalendar({
                type: "date",
                date:postData.start_date,
                format: "YYYY-MM-DD",
                baseClass: "upload-calendar",
                startDate:2010,
                endDate:new Date().getDate()
            },
            function (api) {startTimeApi = api;}
        );
        $endDate.cxCalendar({
                type: "date",
                date:postData.end_date,
                format: "YYYY-MM-DD",
                baseClass: "upload-calendar",
                startDate:2010,
                endDate:new Date().getDate()
            },
            function (api) { endTimeApi = api;}
        );
        $startDate.on("change", function () {
            $(this).closest('.calendar-tab').removeClass('active').addClass('active');
            var startTime = parseInt(startTimeApi.getDate("TIME"), 10);
            var endTime = parseInt(endTimeApi.getDate("TIME"), 10);

            if (endTime < startTime) {
                endTimeApi.clearDate();
            }

            endTimeApi.setOptions({
                startDate: startTime
            });
            endTimeApi.gotoDate(startTime);
            endTimeApi.show();
            console.log('Ok下载startTime',startTime,endTime,'endTime');
        });
         //清除初始日期
         $wrap.on("click", ".J-del-start", function () {
            startTimeApi.clearDate();
            endTimeApi.clearDate();
        });
        //清除结束日期
        $wrap.on("click", ".J-del-end", function () {
            endTimeApi.clearDate();
        });
`
