### ISSUE TITLE
清除日期值，没能彻底清除掉已选中的日期的状态，想还原成初始状态。

### ISSUE THREAD

**Issue by sunny628** [ciaoca/cxCalendar#21]
http://code.ciaoca.com/jquery/cxCalendar/demo/api
你好，
DOM页－－API接口里的示例按钮：
1.点击“”设置日期值（2014.11.29）“
日历输入框显示 2014.11.29 00：00：00

2.点击“”清除日期值“”，日历输入框  为空

3.再点击日历输入框 ，打开日历选择器，
201.11.29 还存在高亮的选中状态，
如下图
![qq 20180601164055](https://user-images.githubusercontent.com/16478878/40831381-6d52b66a-65bb-11e8-93cd-09f65048e531.png)

想去掉它的选中状态，类似还原成初始状态。

用了其它方法解决

**Comment by sunny628** [comment]
双联动的日期，clear之后，
再重新打开结束日期的日历，结束日期的日期5.8号前的不可选。
再重新打开初始日期，初始日期5.8号前 可以选择。 
重新打开的日历当中5.8和5.24都是选中的高亮状态

**Comment by ciaoca** [comment]
已修复该问题
