### ISSUE TITLE
css样式与bootstrap冲突，及一个难以关闭选取框的缺陷修复

### ISSUE THREAD

**Issue by gitSquirel** [ciaoca/cxCalendar#3]
你好，我在项目中使用了你的日期组件，使用中碰到两个问题，反馈给你。

我的项目中同时用了bootstrap，我发现两者之间有点冲突，会导致日期选择框内的内容排列错乱，修复方法如下：
.cxcalendar增加一个样式：box-sizing:content-box;
同时增加一个新的样式：
.cxcalendar *{box-sizing:content-box}
或者您可以大修一下，使其在border-box下正常显示，与bootstrap兼容。

另一个问题，我一开始用的时候发现弹出的选取框没法关闭，只能选了日期后才能关闭，在页面中其它部分点击无法关闭，而你的演示页面上不存在这个问题。找了头天才找到原因，原因是那个遮罩层太小了，而你的演示页面上为body定义了minheight来避免这个问题。这是由于你在定义遮罩层大小时用的是body的宽、高引起的，修复如下：
var docWidth = document.body.clientWidth;
var docHeight = document.body.clientHeight;
改成如下，使用窗口的宽、高：
var docWidth = document.documentElement.clientWidth;
var docHeight = document.documentElement.clientHeight;

**Comment by ciaoca** [comment]
我近期将抽些时间来优化一下，感谢你的反馈。

**Comment by ciaoca** [comment]
已优化样式的兼容性，其实样式是可以自定义的，可以自己美化或调整，不想改默认的样式，也可以通过参数 baseClass 增加自己的 class 来调整样式。
