### ISSUE TITLE
动态加载的数据无法绑定

### ISSUE THREAD

**Issue by Xpig4432xyx** [ciaoca/cxCalendar#7]
动态加载的数据无法绑定 

在页面里点击按钮新增一行tr input name="next_date" /tr，此条<tr>为append（）添加，
$('input[name=next_date]').cxCalendar();无法绑定，在$(document)中也无法绑定，

望指教

**Comment by ciaoca** [comment]
http://sandbox.runjs.cn/show/vf4w4i5r
测试动态添加 DOM，可以正常使用 cxCalendar

**Comment by Xpig4432xyx** [comment]
谢谢指点 因为我用了layer弹出层 z-index层级不够被弹出层挡住了 现已解决
不过好像还有一些小问题 看你的test 动态添加DOM 添加多个input 点击input一下会触发2次cxCalendar，弹出两个div，每次选择日期都有点2下 有的要点3下，并且在我的代码里无法点击使其消失，

望指教

**Comment by ciaoca** [comment]
选择器设置$('input') 是批量的，最好使用 id，或者过滤掉

**Comment by FrankZolala** [comment]
请问一下，选择联动日期的时候两边不能都选当天吗？我想查当天几点到几点的货物，如2017-2-16 11:57到2017-2-16 15:00,
 $(function() {

        $(".dateStart").cxCalendar({
            type:'datetime',
            format:'YYYY-MM-DD HH:mm:ss',
            close: function(selectedDate) {
                $(".dateEnd").cxCalendar("option","minDate",selectedDate);
            }
        });

        $(".dateEnd").cxCalendar({
            type:'datetime',
            format:'YYYY-MM-DD HH:mm:ss',
            close: function(selectedDate) {
                $(".dateStart").cxCalendar("option","maxDate", selectedDate);
            }
        });
    });
求解.

**Comment by ciaoca** [comment]
联动日期可以都选同一天，参考 DEMO：http://code.ciaoca.com/jquery/cxCalendar/demo/api

PS: 不同问题请开新 issue

**Comment by FrankZolala** [comment]
谢谢指点，不好意思，下次我会注意的。
